/* f2-01: literal contract oracle for target-generated ABI data.
 * SPDX-License-Identifier: GPL-2.0-only */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ciuki/abi.h>

struct expectation { const char *key; uint32_t native, expected; };
static const struct expectation expectations[] = {
    {"target.sizeof.char", sizeof(char), 1u},
    {"target.sizeof.short", sizeof(short), 2u},
    {"target.sizeof.int", sizeof(int), 4u},
    {"target.sizeof.long", sizeof(long), 4u},
    {"target.sizeof.long long", sizeof(long long), 8u},
    {"target.sizeof.void *", sizeof(void *), 4u},
    {"target.sizeof.float", sizeof(float), 4u},
    {"target.sizeof.double", sizeof(double), 8u},
    {"target.sizeof.long double", sizeof(long double), 12u},
    {"target.alignof.long double", _Alignof(long double), 4u},
    {"target.char_signed", ((char)-1 < 0), 1u},
    {"constant.CIUKI_ABI_VERSION", (uint32_t)(CIUKI_ABI_VERSION), 1u},
    {"constant.__CIUKI_ABI_VERSION__", (uint32_t)(__CIUKI_ABI_VERSION__), 1u},
    {"constant.__CIUKIOS__", (uint32_t)(__CIUKIOS__), 1u},
    {"constant.EPERM", (uint32_t)(EPERM), 1u},
    {"constant.ENOENT", (uint32_t)(ENOENT), 2u},
    {"constant.ESRCH", (uint32_t)(ESRCH), 3u},
    {"constant.EINTR", (uint32_t)(EINTR), 4u},
    {"constant.EIO", (uint32_t)(EIO), 5u},
    {"constant.ENXIO", (uint32_t)(ENXIO), 6u},
    {"constant.E2BIG", (uint32_t)(E2BIG), 7u},
    {"constant.ENOEXEC", (uint32_t)(ENOEXEC), 8u},
    {"constant.EBADF", (uint32_t)(EBADF), 9u},
    {"constant.ECHILD", (uint32_t)(ECHILD), 10u},
    {"constant.EAGAIN", (uint32_t)(EAGAIN), 11u},
    {"constant.ENOMEM", (uint32_t)(ENOMEM), 12u},
    {"constant.EACCES", (uint32_t)(EACCES), 13u},
    {"constant.EFAULT", (uint32_t)(EFAULT), 14u},
    {"constant.EBUSY", (uint32_t)(EBUSY), 16u},
    {"constant.EEXIST", (uint32_t)(EEXIST), 17u},
    {"constant.EXDEV", (uint32_t)(EXDEV), 18u},
    {"constant.ENODEV", (uint32_t)(ENODEV), 19u},
    {"constant.ENOTDIR", (uint32_t)(ENOTDIR), 20u},
    {"constant.EISDIR", (uint32_t)(EISDIR), 21u},
    {"constant.EINVAL", (uint32_t)(EINVAL), 22u},
    {"constant.ENFILE", (uint32_t)(ENFILE), 23u},
    {"constant.EMFILE", (uint32_t)(EMFILE), 24u},
    {"constant.ENOTTY", (uint32_t)(ENOTTY), 25u},
    {"constant.ETXTBSY", (uint32_t)(ETXTBSY), 26u},
    {"constant.EFBIG", (uint32_t)(EFBIG), 27u},
    {"constant.ENOSPC", (uint32_t)(ENOSPC), 28u},
    {"constant.ESPIPE", (uint32_t)(ESPIPE), 29u},
    {"constant.EROFS", (uint32_t)(EROFS), 30u},
    {"constant.EPIPE", (uint32_t)(EPIPE), 32u},
    {"constant.EDOM", (uint32_t)(EDOM), 33u},
    {"constant.ERANGE", (uint32_t)(ERANGE), 34u},
    {"constant.EDEADLK", (uint32_t)(EDEADLK), 35u},
    {"constant.ENAMETOOLONG", (uint32_t)(ENAMETOOLONG), 36u},
    {"constant.ENOSYS", (uint32_t)(ENOSYS), 38u},
    {"constant.ENOTEMPTY", (uint32_t)(ENOTEMPTY), 39u},
    {"constant.EOVERFLOW", (uint32_t)(EOVERFLOW), 75u},
    {"constant.EILSEQ", (uint32_t)(EILSEQ), 84u},
    {"constant.EMSGSIZE", (uint32_t)(EMSGSIZE), 90u},
    {"constant.EOPNOTSUPP", (uint32_t)(EOPNOTSUPP), 95u},
    {"constant.ETIMEDOUT", (uint32_t)(ETIMEDOUT), 110u},
    {"constant.ECANCELED", (uint32_t)(ECANCELED), 125u},
    {"constant.EWOULDBLOCK", (uint32_t)(EWOULDBLOCK), 11u},
    {"constant.ENOTSUP", (uint32_t)(ENOTSUP), 95u},
    {"constant.CIUKI_EPERM", (uint32_t)(CIUKI_EPERM), 1u},
    {"constant.CIUKI_ENOENT", (uint32_t)(CIUKI_ENOENT), 2u},
    {"constant.CIUKI_ESRCH", (uint32_t)(CIUKI_ESRCH), 3u},
    {"constant.CIUKI_EINTR", (uint32_t)(CIUKI_EINTR), 4u},
    {"constant.CIUKI_EIO", (uint32_t)(CIUKI_EIO), 5u},
    {"constant.CIUKI_ENXIO", (uint32_t)(CIUKI_ENXIO), 6u},
    {"constant.CIUKI_E2BIG", (uint32_t)(CIUKI_E2BIG), 7u},
    {"constant.CIUKI_ENOEXEC", (uint32_t)(CIUKI_ENOEXEC), 8u},
    {"constant.CIUKI_EBADF", (uint32_t)(CIUKI_EBADF), 9u},
    {"constant.CIUKI_ECHILD", (uint32_t)(CIUKI_ECHILD), 10u},
    {"constant.CIUKI_EAGAIN", (uint32_t)(CIUKI_EAGAIN), 11u},
    {"constant.CIUKI_ENOMEM", (uint32_t)(CIUKI_ENOMEM), 12u},
    {"constant.CIUKI_EACCES", (uint32_t)(CIUKI_EACCES), 13u},
    {"constant.CIUKI_EFAULT", (uint32_t)(CIUKI_EFAULT), 14u},
    {"constant.CIUKI_EBUSY", (uint32_t)(CIUKI_EBUSY), 16u},
    {"constant.CIUKI_EEXIST", (uint32_t)(CIUKI_EEXIST), 17u},
    {"constant.CIUKI_EXDEV", (uint32_t)(CIUKI_EXDEV), 18u},
    {"constant.CIUKI_ENODEV", (uint32_t)(CIUKI_ENODEV), 19u},
    {"constant.CIUKI_ENOTDIR", (uint32_t)(CIUKI_ENOTDIR), 20u},
    {"constant.CIUKI_EISDIR", (uint32_t)(CIUKI_EISDIR), 21u},
    {"constant.CIUKI_EINVAL", (uint32_t)(CIUKI_EINVAL), 22u},
    {"constant.CIUKI_ENFILE", (uint32_t)(CIUKI_ENFILE), 23u},
    {"constant.CIUKI_EMFILE", (uint32_t)(CIUKI_EMFILE), 24u},
    {"constant.CIUKI_ENOTTY", (uint32_t)(CIUKI_ENOTTY), 25u},
    {"constant.CIUKI_ETXTBSY", (uint32_t)(CIUKI_ETXTBSY), 26u},
    {"constant.CIUKI_EFBIG", (uint32_t)(CIUKI_EFBIG), 27u},
    {"constant.CIUKI_ENOSPC", (uint32_t)(CIUKI_ENOSPC), 28u},
    {"constant.CIUKI_ESPIPE", (uint32_t)(CIUKI_ESPIPE), 29u},
    {"constant.CIUKI_EROFS", (uint32_t)(CIUKI_EROFS), 30u},
    {"constant.CIUKI_EPIPE", (uint32_t)(CIUKI_EPIPE), 32u},
    {"constant.CIUKI_EDOM", (uint32_t)(CIUKI_EDOM), 33u},
    {"constant.CIUKI_ERANGE", (uint32_t)(CIUKI_ERANGE), 34u},
    {"constant.CIUKI_EDEADLK", (uint32_t)(CIUKI_EDEADLK), 35u},
    {"constant.CIUKI_ENAMETOOLONG", (uint32_t)(CIUKI_ENAMETOOLONG), 36u},
    {"constant.CIUKI_ENOSYS", (uint32_t)(CIUKI_ENOSYS), 38u},
    {"constant.CIUKI_ENOTEMPTY", (uint32_t)(CIUKI_ENOTEMPTY), 39u},
    {"constant.CIUKI_EOVERFLOW", (uint32_t)(CIUKI_EOVERFLOW), 75u},
    {"constant.CIUKI_EILSEQ", (uint32_t)(CIUKI_EILSEQ), 84u},
    {"constant.CIUKI_EMSGSIZE", (uint32_t)(CIUKI_EMSGSIZE), 90u},
    {"constant.CIUKI_EOPNOTSUPP", (uint32_t)(CIUKI_EOPNOTSUPP), 95u},
    {"constant.CIUKI_ETIMEDOUT", (uint32_t)(CIUKI_ETIMEDOUT), 110u},
    {"constant.CIUKI_ECANCELED", (uint32_t)(CIUKI_ECANCELED), 125u},
    {"constant.CIUKI_EWOULDBLOCK", (uint32_t)(CIUKI_EWOULDBLOCK), 11u},
    {"constant.CIUKI_ENOTSUP", (uint32_t)(CIUKI_ENOTSUP), 95u},
    {"constant.O_RDONLY", (uint32_t)(O_RDONLY), 0u},
    {"constant.O_WRONLY", (uint32_t)(O_WRONLY), 1u},
    {"constant.O_RDWR", (uint32_t)(O_RDWR), 2u},
    {"constant.O_ACCMODE", (uint32_t)(O_ACCMODE), 3u},
    {"constant.O_CREAT", (uint32_t)(O_CREAT), 64u},
    {"constant.O_EXCL", (uint32_t)(O_EXCL), 128u},
    {"constant.O_TRUNC", (uint32_t)(O_TRUNC), 512u},
    {"constant.O_APPEND", (uint32_t)(O_APPEND), 1024u},
    {"constant.O_NONBLOCK", (uint32_t)(O_NONBLOCK), 2048u},
    {"constant.O_DIRECTORY", (uint32_t)(O_DIRECTORY), 65536u},
    {"constant.O_CLOEXEC", (uint32_t)(O_CLOEXEC), 524288u},
    {"constant.F_DUPFD", (uint32_t)(F_DUPFD), 0u},
    {"constant.F_GETFD", (uint32_t)(F_GETFD), 1u},
    {"constant.F_SETFD", (uint32_t)(F_SETFD), 2u},
    {"constant.F_GETFL", (uint32_t)(F_GETFL), 3u},
    {"constant.F_SETFL", (uint32_t)(F_SETFL), 4u},
    {"constant.F_DUPFD_CLOEXEC", (uint32_t)(F_DUPFD_CLOEXEC), 1030u},
    {"constant.FD_CLOEXEC", (uint32_t)(FD_CLOEXEC), 1u},
    {"constant.SEEK_SET", (uint32_t)(SEEK_SET), 0u},
    {"constant.SEEK_CUR", (uint32_t)(SEEK_CUR), 1u},
    {"constant.SEEK_END", (uint32_t)(SEEK_END), 2u},
    {"constant.S_IFMT", (uint32_t)(S_IFMT), 61440u},
    {"constant.S_IFREG", (uint32_t)(S_IFREG), 32768u},
    {"constant.S_IFDIR", (uint32_t)(S_IFDIR), 16384u},
    {"constant.S_IFCHR", (uint32_t)(S_IFCHR), 8192u},
    {"constant.PROT_NONE", (uint32_t)(PROT_NONE), 0u},
    {"constant.PROT_READ", (uint32_t)(PROT_READ), 1u},
    {"constant.PROT_WRITE", (uint32_t)(PROT_WRITE), 2u},
    {"constant.PROT_EXEC", (uint32_t)(PROT_EXEC), 4u},
    {"constant.MAP_SHARED", (uint32_t)(MAP_SHARED), 1u},
    {"constant.MAP_PRIVATE", (uint32_t)(MAP_PRIVATE), 2u},
    {"constant.MAP_FIXED", (uint32_t)(MAP_FIXED), 16u},
    {"constant.MAP_ANONYMOUS", (uint32_t)(MAP_ANONYMOUS), 32u},
    {"constant.MAP_FAILED", (uint32_t)(MAP_FAILED), 4294967295u},
    {"constant.CLOCK_REALTIME", (uint32_t)(CLOCK_REALTIME), 0u},
    {"constant.CLOCK_MONOTONIC", (uint32_t)(CLOCK_MONOTONIC), 1u},
    {"constant.CLOCK_PROCESS_CPUTIME_ID", (uint32_t)(CLOCK_PROCESS_CPUTIME_ID), 2u},
    {"constant.WNOHANG", (uint32_t)(WNOHANG), 1u},
    {"constant.CIUKI_SPAWN_NEW_GROUP", (uint32_t)(CIUKI_SPAWN_NEW_GROUP), 1u},
    {"constant.CIUKI_THREAD_DETACHED", (uint32_t)(CIUKI_THREAD_DETACHED), 1u},
    {"constant._SC_PAGESIZE", (uint32_t)(_SC_PAGESIZE), 1u},
    {"constant._SC_OPEN_MAX", (uint32_t)(_SC_OPEN_MAX), 2u},
    {"constant._SC_ARG_MAX", (uint32_t)(_SC_ARG_MAX), 3u},
    {"constant._SC_THREAD_KEYS_MAX", (uint32_t)(_SC_THREAD_KEYS_MAX), 4u},
    {"constant._SC_THREAD_STACK_MIN", (uint32_t)(_SC_THREAD_STACK_MIN), 5u},
    {"constant.CLOCKS_PER_SEC", (uint32_t)(CLOCKS_PER_SEC), 1000000u},
    {"constant.CIUKI_SC_PAGESIZE_VALUE", (uint32_t)(CIUKI_SC_PAGESIZE_VALUE), 4096u},
    {"constant.CIUKI_SC_OPEN_MAX_VALUE", (uint32_t)(CIUKI_SC_OPEN_MAX_VALUE), 128u},
    {"constant.CIUKI_SC_ARG_MAX_VALUE", (uint32_t)(CIUKI_SC_ARG_MAX_VALUE), 65536u},
    {"constant.CIUKI_SC_THREAD_KEYS_MAX_VALUE", (uint32_t)(CIUKI_SC_THREAD_KEYS_MAX_VALUE), 64u},
    {"constant.CIUKI_SC_THREAD_STACK_MIN_VALUE", (uint32_t)(CIUKI_SC_THREAD_STACK_MIN_VALUE), 65536u},
    {"constant.SIG_BLOCK", (uint32_t)(SIG_BLOCK), 0u},
    {"constant.SIG_UNBLOCK", (uint32_t)(SIG_UNBLOCK), 1u},
    {"constant.SIG_SETMASK", (uint32_t)(SIG_SETMASK), 2u},
    {"constant.SIG_DFL", (uint32_t)(SIG_DFL), 0u},
    {"constant.SIG_IGN", (uint32_t)(SIG_IGN), 1u},
    {"constant.SA_SIGINFO", (uint32_t)(SA_SIGINFO), 4u},
    {"constant.SIGINT", (uint32_t)(SIGINT), 2u},
    {"constant.SIGILL", (uint32_t)(SIGILL), 4u},
    {"constant.SIGABRT", (uint32_t)(SIGABRT), 6u},
    {"constant.SIGBUS", (uint32_t)(SIGBUS), 7u},
    {"constant.SIGFPE", (uint32_t)(SIGFPE), 8u},
    {"constant.SIGKILL", (uint32_t)(SIGKILL), 9u},
    {"constant.SIGUSR1", (uint32_t)(SIGUSR1), 10u},
    {"constant.SIGSEGV", (uint32_t)(SIGSEGV), 11u},
    {"constant.SIGUSR2", (uint32_t)(SIGUSR2), 12u},
    {"constant.SIGPIPE", (uint32_t)(SIGPIPE), 13u},
    {"constant.SIGTERM", (uint32_t)(SIGTERM), 15u},
    {"constant.SIGCHLD", (uint32_t)(SIGCHLD), 17u},
    {"constant.DT_DIR", (uint32_t)(DT_DIR), 4u},
    {"constant.DT_REG", (uint32_t)(DT_REG), 8u},
    {"constant.DT_CHR", (uint32_t)(DT_CHR), 2u},
    {"constant.DT_UNKNOWN", (uint32_t)(DT_UNKNOWN), 0u},
    {"constant.AT_PAGESZ", (uint32_t)(AT_PAGESZ), 6u},
    {"constant.AT_ENTRY", (uint32_t)(AT_ENTRY), 9u},
    {"constant.AT_CIUKI_TLS", (uint32_t)(AT_CIUKI_TLS), 1610612737u},
    {"constant.AT_CIUKI_TLS_SIZE", (uint32_t)(AT_CIUKI_TLS_SIZE), 1610612738u},
    {"constant.AT_CIUKI_ABI", (uint32_t)(AT_CIUKI_ABI), 1610612739u},
    {"constant.AT_NULL", (uint32_t)(AT_NULL), 0u},
    {"constant.CIUKI_PATH_MAX", (uint32_t)(CIUKI_PATH_MAX), 1040u},
    {"constant.CIUKI_NAME_MAX", (uint32_t)(CIUKI_NAME_MAX), 765u},
    {"constant.CIUKI_ARG_MAX", (uint32_t)(CIUKI_ARG_MAX), 65536u},
    {"constant.CIUKI_OPEN_MAX", (uint32_t)(CIUKI_OPEN_MAX), 128u},
    {"constant.CIUKI_PROCESS_MAX", (uint32_t)(CIUKI_PROCESS_MAX), 64u},
    {"constant.CIUKI_THREAD_MAX", (uint32_t)(CIUKI_THREAD_MAX), 256u},
    {"constant.CIUKI_PROCESS_THREAD_MAX", (uint32_t)(CIUKI_PROCESS_THREAD_MAX), 16u},
    {"constant.CIUKI_OPEN_DESCRIPTION_MAX", (uint32_t)(CIUKI_OPEN_DESCRIPTION_MAX), 1024u},
    {"constant.CIUKI_MAPPING_MAX", (uint32_t)(CIUKI_MAPPING_MAX), 256u},
    {"constant.CIUKI_IO_MAX", (uint32_t)(CIUKI_IO_MAX), 1048576u},
    {"constant.CIUKI_SURFACE_MAX", (uint32_t)(CIUKI_SURFACE_MAX), 16777216u},
    {"constant.CIUKI_MESSAGE_PAYLOAD_MAX", (uint32_t)(CIUKI_MESSAGE_PAYLOAD_MAX), 256u},
    {"constant.CIUKI_MESSAGE_FD_MAX", (uint32_t)(CIUKI_MESSAGE_FD_MAX), 4u},
    {"constant.CIUKI_CHANNEL_QUEUE_MAX", (uint32_t)(CIUKI_CHANNEL_QUEUE_MAX), 64u},
    {"constant.CIUKI_INPUT_QUEUE_MAX", (uint32_t)(CIUKI_INPUT_QUEUE_MAX), 256u},
    {"constant.CIUKI_INPUT_READ_MAX", (uint32_t)(CIUKI_INPUT_READ_MAX), 64u},
    {"constant.CIUKI_ARGV_MAX", (uint32_t)(CIUKI_ARGV_MAX), 256u},
    {"constant.CIUKI_ENVP_MAX", (uint32_t)(CIUKI_ENVP_MAX), 256u},
    {"constant.CIUKI_GETDENTS_MIN", (uint32_t)(CIUKI_GETDENTS_MIN), 792u},
    {"constant.CIUKI_GETDENTS_MAX", (uint32_t)(CIUKI_GETDENTS_MAX), 65536u},
    {"constant.CIUKI_PAGE_SIZE", (uint32_t)(CIUKI_PAGE_SIZE), 4096u},
    {"constant.CIUKI_TLS_SIZE", (uint32_t)(CIUKI_TLS_SIZE), 4096u},
    {"constant.CIUKI_TLS_SELECTOR", (uint32_t)(CIUKI_TLS_SELECTOR), 59u},
    {"constant.CIUKI_TLS_GDT_INDEX", (uint32_t)(CIUKI_TLS_GDT_INDEX), 7u},
    {"constant.CIUKI_THREAD_STACK_MIN", (uint32_t)(CIUKI_THREAD_STACK_MIN), 65536u},
    {"constant.CIUKI_THREAD_STACK_DEFAULT", (uint32_t)(CIUKI_THREAD_STACK_DEFAULT), 1048576u},
    {"constant.CIUKI_THREAD_STACK_MAX", (uint32_t)(CIUKI_THREAD_STACK_MAX), 4194304u},
    {"constant.CIUKI_THREAD_KEYS_MAX", (uint32_t)(CIUKI_THREAD_KEYS_MAX), 64u},
    {"constant.CIUKI_THREAD_DESTRUCTOR_ITERATIONS", (uint32_t)(CIUKI_THREAD_DESTRUCTOR_ITERATIONS), 4u},
    {"constant.CIUKI_ELF_PHDR_MAX", (uint32_t)(CIUKI_ELF_PHDR_MAX), 16u},
    {"constant.CIUKI_ELF_BYTES_MAX", (uint32_t)(CIUKI_ELF_BYTES_MAX), 33554432u},
    {"constant.CIUKI_IMAGE_BASE", (uint32_t)(CIUKI_IMAGE_BASE), 4194304u},
    {"constant.CIUKI_IMAGE_LIMIT", (uint32_t)(CIUKI_IMAGE_LIMIT), 268435456u},
    {"constant.CIUKI_HEAP_LIMIT", (uint32_t)(CIUKI_HEAP_LIMIT), 536870912u},
    {"constant.CIUKI_MMAP_BASE", (uint32_t)(CIUKI_MMAP_BASE), 536870912u},
    {"constant.CIUKI_MMAP_LIMIT", (uint32_t)(CIUKI_MMAP_LIMIT), 3217031168u},
    {"constant.CIUKI_MAIN_STACK_BASE", (uint32_t)(CIUKI_MAIN_STACK_BASE), 3220176896u},
    {"constant.CIUKI_MAIN_STACK_LIMIT", (uint32_t)(CIUKI_MAIN_STACK_LIMIT), 3221225472u},
    {"constant.CIUKI_MAIN_STACK_RESERVATION_BASE", (uint32_t)(CIUKI_MAIN_STACK_RESERVATION_BASE), 3217031168u},
    {"constant.CIUKI_MAIN_STACK_GUARD_BASE", (uint32_t)(CIUKI_MAIN_STACK_GUARD_BASE), 3220172800u},
    {"constant.CIUKI_INITIAL_EFLAGS", (uint32_t)(CIUKI_INITIAL_EFLAGS), 514u},
    {"constant.CIUKI_SYSCALL_ERROR_MAX", (uint32_t)(CIUKI_SYSCALL_ERROR_MAX), 4095u},
    {"constant.CIUKI_ID_MAX", (uint32_t)(CIUKI_ID_MAX), 2147483647u},
    {"constant.CIUKI_DEBUG_WRITE_MAX", (uint32_t)(CIUKI_DEBUG_WRITE_MAX), 240u},
    {"constant.CIUKI_PROBE_REPORT_MAX", (uint32_t)(CIUKI_PROBE_REPORT_MAX), 240u},
    {"constant.CIUKI_SLEEP_MS_MAX", (uint32_t)(CIUKI_SLEEP_MS_MAX), 60000u},
    {"constant.CIUKI_PROBE_QUERY_MAX", (uint32_t)(CIUKI_PROBE_QUERY_MAX), 4096u},
    {"constant.CIUKI_SURFACE_XRGB8888", (uint32_t)(CIUKI_SURFACE_XRGB8888), 1u},
    {"constant.CIUKI_SURFACE_DIMENSION_MAX", (uint32_t)(CIUKI_SURFACE_DIMENSION_MAX), 2048u},
    {"constant.CIUKI_SURFACE_PIXEL_BYTES", (uint32_t)(CIUKI_SURFACE_PIXEL_BYTES), 4u},
    {"constant.DONTWAIT", (uint32_t)(DONTWAIT), 1u},
    {"constant.CIUKI_INPUT_KEY", (uint32_t)(CIUKI_INPUT_KEY), 1u},
    {"constant.CIUKI_INPUT_TEXT", (uint32_t)(CIUKI_INPUT_TEXT), 2u},
    {"constant.CIUKI_INPUT_MOTION", (uint32_t)(CIUKI_INPUT_MOTION), 3u},
    {"constant.CIUKI_INPUT_BUTTON", (uint32_t)(CIUKI_INPUT_BUTTON), 4u},
    {"constant.CIUKI_INPUT_RESYNC", (uint32_t)(CIUKI_INPUT_RESYNC), 5u},
    {"constant.CIUKI_KEY_VALUE_UP", (uint32_t)(CIUKI_KEY_VALUE_UP), 0u},
    {"constant.CIUKI_KEY_VALUE_DOWN", (uint32_t)(CIUKI_KEY_VALUE_DOWN), 1u},
    {"constant.CIUKI_KEY_VALUE_REPEAT", (uint32_t)(CIUKI_KEY_VALUE_REPEAT), 2u},
    {"constant.CIUKI_BUTTON_LEFT", (uint32_t)(CIUKI_BUTTON_LEFT), 1u},
    {"constant.CIUKI_BUTTON_RIGHT", (uint32_t)(CIUKI_BUTTON_RIGHT), 2u},
    {"constant.CIUKI_BUTTON_MIDDLE", (uint32_t)(CIUKI_BUTTON_MIDDLE), 3u},
    {"constant.CIUKI_FP_FNSAVE", (uint32_t)(CIUKI_FP_FNSAVE), 1u},
    {"constant.SEGV_MAPERR", (uint32_t)(SEGV_MAPERR), 1u},
    {"constant.ILL_ILLOPC", (uint32_t)(ILL_ILLOPC), 1u},
    {"constant.BUS_ADRALN", (uint32_t)(BUS_ADRALN), 1u},
    {"constant.FPE_INTDIV", (uint32_t)(FPE_INTDIV), 1u},
    {"constant.SEGV_ACCERR", (uint32_t)(SEGV_ACCERR), 2u},
    {"constant.CIUKI_SI_X87", (uint32_t)(CIUKI_SI_X87), 7u},
    {"constant.CIUKI_PTHREAD_MUTEX_NORMAL", (uint32_t)(CIUKI_PTHREAD_MUTEX_NORMAL), 0u},
    {"constant.CIUKI_PTHREAD_MUTEX_RECURSIVE", (uint32_t)(CIUKI_PTHREAD_MUTEX_RECURSIVE), 1u},
    {"constant.CIUKI_KEY_ESCAPE", (uint32_t)(CIUKI_KEY_ESCAPE), 1u},
    {"constant.CIUKI_KEY_1", (uint32_t)(CIUKI_KEY_1), 2u},
    {"constant.CIUKI_KEY_2", (uint32_t)(CIUKI_KEY_2), 3u},
    {"constant.CIUKI_KEY_3", (uint32_t)(CIUKI_KEY_3), 4u},
    {"constant.CIUKI_KEY_4", (uint32_t)(CIUKI_KEY_4), 5u},
    {"constant.CIUKI_KEY_5", (uint32_t)(CIUKI_KEY_5), 6u},
    {"constant.CIUKI_KEY_6", (uint32_t)(CIUKI_KEY_6), 7u},
    {"constant.CIUKI_KEY_7", (uint32_t)(CIUKI_KEY_7), 8u},
    {"constant.CIUKI_KEY_8", (uint32_t)(CIUKI_KEY_8), 9u},
    {"constant.CIUKI_KEY_9", (uint32_t)(CIUKI_KEY_9), 10u},
    {"constant.CIUKI_KEY_0", (uint32_t)(CIUKI_KEY_0), 11u},
    {"constant.CIUKI_KEY_MINUS", (uint32_t)(CIUKI_KEY_MINUS), 12u},
    {"constant.CIUKI_KEY_EQUAL", (uint32_t)(CIUKI_KEY_EQUAL), 13u},
    {"constant.CIUKI_KEY_BACKSPACE", (uint32_t)(CIUKI_KEY_BACKSPACE), 14u},
    {"constant.CIUKI_KEY_TAB", (uint32_t)(CIUKI_KEY_TAB), 15u},
    {"constant.CIUKI_KEY_Q", (uint32_t)(CIUKI_KEY_Q), 16u},
    {"constant.CIUKI_KEY_W", (uint32_t)(CIUKI_KEY_W), 17u},
    {"constant.CIUKI_KEY_E", (uint32_t)(CIUKI_KEY_E), 18u},
    {"constant.CIUKI_KEY_R", (uint32_t)(CIUKI_KEY_R), 19u},
    {"constant.CIUKI_KEY_T", (uint32_t)(CIUKI_KEY_T), 20u},
    {"constant.CIUKI_KEY_Y", (uint32_t)(CIUKI_KEY_Y), 21u},
    {"constant.CIUKI_KEY_U", (uint32_t)(CIUKI_KEY_U), 22u},
    {"constant.CIUKI_KEY_I", (uint32_t)(CIUKI_KEY_I), 23u},
    {"constant.CIUKI_KEY_O", (uint32_t)(CIUKI_KEY_O), 24u},
    {"constant.CIUKI_KEY_P", (uint32_t)(CIUKI_KEY_P), 25u},
    {"constant.CIUKI_KEY_LEFTBRACKET", (uint32_t)(CIUKI_KEY_LEFTBRACKET), 26u},
    {"constant.CIUKI_KEY_RIGHTBRACKET", (uint32_t)(CIUKI_KEY_RIGHTBRACKET), 27u},
    {"constant.CIUKI_KEY_ENTER", (uint32_t)(CIUKI_KEY_ENTER), 28u},
    {"constant.CIUKI_KEY_LEFTCTRL", (uint32_t)(CIUKI_KEY_LEFTCTRL), 29u},
    {"constant.CIUKI_KEY_A", (uint32_t)(CIUKI_KEY_A), 30u},
    {"constant.CIUKI_KEY_S", (uint32_t)(CIUKI_KEY_S), 31u},
    {"constant.CIUKI_KEY_D", (uint32_t)(CIUKI_KEY_D), 32u},
    {"constant.CIUKI_KEY_F", (uint32_t)(CIUKI_KEY_F), 33u},
    {"constant.CIUKI_KEY_G", (uint32_t)(CIUKI_KEY_G), 34u},
    {"constant.CIUKI_KEY_H", (uint32_t)(CIUKI_KEY_H), 35u},
    {"constant.CIUKI_KEY_J", (uint32_t)(CIUKI_KEY_J), 36u},
    {"constant.CIUKI_KEY_K", (uint32_t)(CIUKI_KEY_K), 37u},
    {"constant.CIUKI_KEY_L", (uint32_t)(CIUKI_KEY_L), 38u},
    {"constant.CIUKI_KEY_SEMICOLON", (uint32_t)(CIUKI_KEY_SEMICOLON), 39u},
    {"constant.CIUKI_KEY_APOSTROPHE", (uint32_t)(CIUKI_KEY_APOSTROPHE), 40u},
    {"constant.CIUKI_KEY_GRAVE", (uint32_t)(CIUKI_KEY_GRAVE), 41u},
    {"constant.CIUKI_KEY_LEFTSHIFT", (uint32_t)(CIUKI_KEY_LEFTSHIFT), 42u},
    {"constant.CIUKI_KEY_BACKSLASH", (uint32_t)(CIUKI_KEY_BACKSLASH), 43u},
    {"constant.CIUKI_KEY_Z", (uint32_t)(CIUKI_KEY_Z), 44u},
    {"constant.CIUKI_KEY_X", (uint32_t)(CIUKI_KEY_X), 45u},
    {"constant.CIUKI_KEY_C", (uint32_t)(CIUKI_KEY_C), 46u},
    {"constant.CIUKI_KEY_V", (uint32_t)(CIUKI_KEY_V), 47u},
    {"constant.CIUKI_KEY_B", (uint32_t)(CIUKI_KEY_B), 48u},
    {"constant.CIUKI_KEY_N", (uint32_t)(CIUKI_KEY_N), 49u},
    {"constant.CIUKI_KEY_M", (uint32_t)(CIUKI_KEY_M), 50u},
    {"constant.CIUKI_KEY_COMMA", (uint32_t)(CIUKI_KEY_COMMA), 51u},
    {"constant.CIUKI_KEY_PERIOD", (uint32_t)(CIUKI_KEY_PERIOD), 52u},
    {"constant.CIUKI_KEY_SLASH", (uint32_t)(CIUKI_KEY_SLASH), 53u},
    {"constant.CIUKI_KEY_RIGHTSHIFT", (uint32_t)(CIUKI_KEY_RIGHTSHIFT), 54u},
    {"constant.CIUKI_KEY_KP_MULTIPLY", (uint32_t)(CIUKI_KEY_KP_MULTIPLY), 55u},
    {"constant.CIUKI_KEY_LEFTALT", (uint32_t)(CIUKI_KEY_LEFTALT), 56u},
    {"constant.CIUKI_KEY_SPACE", (uint32_t)(CIUKI_KEY_SPACE), 57u},
    {"constant.CIUKI_KEY_CAPSLOCK", (uint32_t)(CIUKI_KEY_CAPSLOCK), 58u},
    {"constant.CIUKI_KEY_F1", (uint32_t)(CIUKI_KEY_F1), 59u},
    {"constant.CIUKI_KEY_F2", (uint32_t)(CIUKI_KEY_F2), 60u},
    {"constant.CIUKI_KEY_F3", (uint32_t)(CIUKI_KEY_F3), 61u},
    {"constant.CIUKI_KEY_F4", (uint32_t)(CIUKI_KEY_F4), 62u},
    {"constant.CIUKI_KEY_F5", (uint32_t)(CIUKI_KEY_F5), 63u},
    {"constant.CIUKI_KEY_F6", (uint32_t)(CIUKI_KEY_F6), 64u},
    {"constant.CIUKI_KEY_F7", (uint32_t)(CIUKI_KEY_F7), 65u},
    {"constant.CIUKI_KEY_F8", (uint32_t)(CIUKI_KEY_F8), 66u},
    {"constant.CIUKI_KEY_F9", (uint32_t)(CIUKI_KEY_F9), 67u},
    {"constant.CIUKI_KEY_F10", (uint32_t)(CIUKI_KEY_F10), 68u},
    {"constant.CIUKI_KEY_NUMLOCK", (uint32_t)(CIUKI_KEY_NUMLOCK), 69u},
    {"constant.CIUKI_KEY_SCROLLLOCK", (uint32_t)(CIUKI_KEY_SCROLLLOCK), 70u},
    {"constant.CIUKI_KEY_KP_7", (uint32_t)(CIUKI_KEY_KP_7), 71u},
    {"constant.CIUKI_KEY_KP_8", (uint32_t)(CIUKI_KEY_KP_8), 72u},
    {"constant.CIUKI_KEY_KP_9", (uint32_t)(CIUKI_KEY_KP_9), 73u},
    {"constant.CIUKI_KEY_KP_MINUS", (uint32_t)(CIUKI_KEY_KP_MINUS), 74u},
    {"constant.CIUKI_KEY_KP_4", (uint32_t)(CIUKI_KEY_KP_4), 75u},
    {"constant.CIUKI_KEY_KP_5", (uint32_t)(CIUKI_KEY_KP_5), 76u},
    {"constant.CIUKI_KEY_KP_6", (uint32_t)(CIUKI_KEY_KP_6), 77u},
    {"constant.CIUKI_KEY_KP_PLUS", (uint32_t)(CIUKI_KEY_KP_PLUS), 78u},
    {"constant.CIUKI_KEY_KP_1", (uint32_t)(CIUKI_KEY_KP_1), 79u},
    {"constant.CIUKI_KEY_KP_2", (uint32_t)(CIUKI_KEY_KP_2), 80u},
    {"constant.CIUKI_KEY_KP_3", (uint32_t)(CIUKI_KEY_KP_3), 81u},
    {"constant.CIUKI_KEY_KP_0", (uint32_t)(CIUKI_KEY_KP_0), 82u},
    {"constant.CIUKI_KEY_KP_PERIOD", (uint32_t)(CIUKI_KEY_KP_PERIOD), 83u},
    {"constant.CIUKI_KEY_102ND", (uint32_t)(CIUKI_KEY_102ND), 86u},
    {"constant.CIUKI_KEY_F11", (uint32_t)(CIUKI_KEY_F11), 87u},
    {"constant.CIUKI_KEY_F12", (uint32_t)(CIUKI_KEY_F12), 88u},
    {"constant.CIUKI_KEY_KP_ENTER", (uint32_t)(CIUKI_KEY_KP_ENTER), 284u},
    {"constant.CIUKI_KEY_RIGHTCTRL", (uint32_t)(CIUKI_KEY_RIGHTCTRL), 285u},
    {"constant.CIUKI_KEY_KP_DIVIDE", (uint32_t)(CIUKI_KEY_KP_DIVIDE), 309u},
    {"constant.CIUKI_KEY_PRINTSCREEN", (uint32_t)(CIUKI_KEY_PRINTSCREEN), 311u},
    {"constant.CIUKI_KEY_RIGHTALT", (uint32_t)(CIUKI_KEY_RIGHTALT), 312u},
    {"constant.CIUKI_KEY_HOME", (uint32_t)(CIUKI_KEY_HOME), 327u},
    {"constant.CIUKI_KEY_UP", (uint32_t)(CIUKI_KEY_UP), 328u},
    {"constant.CIUKI_KEY_PAGEUP", (uint32_t)(CIUKI_KEY_PAGEUP), 329u},
    {"constant.CIUKI_KEY_LEFT", (uint32_t)(CIUKI_KEY_LEFT), 331u},
    {"constant.CIUKI_KEY_RIGHT", (uint32_t)(CIUKI_KEY_RIGHT), 333u},
    {"constant.CIUKI_KEY_END", (uint32_t)(CIUKI_KEY_END), 335u},
    {"constant.CIUKI_KEY_DOWN", (uint32_t)(CIUKI_KEY_DOWN), 336u},
    {"constant.CIUKI_KEY_PAGEDOWN", (uint32_t)(CIUKI_KEY_PAGEDOWN), 337u},
    {"constant.CIUKI_KEY_INSERT", (uint32_t)(CIUKI_KEY_INSERT), 338u},
    {"constant.CIUKI_KEY_DELETE", (uint32_t)(CIUKI_KEY_DELETE), 339u},
    {"constant.CIUKI_KEY_LEFTMETA", (uint32_t)(CIUKI_KEY_LEFTMETA), 347u},
    {"constant.CIUKI_KEY_RIGHTMETA", (uint32_t)(CIUKI_KEY_RIGHTMETA), 348u},
    {"constant.CIUKI_KEY_MENU", (uint32_t)(CIUKI_KEY_MENU), 349u},
    {"constant.CIUKI_KEY_PAUSE", (uint32_t)(CIUKI_KEY_PAUSE), 512u},
    {"constant.CIUKI_KEY_E0", (uint32_t)(CIUKI_KEY_E0), 256u},
    {"constant.CIUKI_REG_GS", (uint32_t)(CIUKI_REG_GS), 0u},
    {"constant.CIUKI_REG_FS", (uint32_t)(CIUKI_REG_FS), 1u},
    {"constant.CIUKI_REG_ES", (uint32_t)(CIUKI_REG_ES), 2u},
    {"constant.CIUKI_REG_DS", (uint32_t)(CIUKI_REG_DS), 3u},
    {"constant.CIUKI_REG_EDI", (uint32_t)(CIUKI_REG_EDI), 4u},
    {"constant.CIUKI_REG_ESI", (uint32_t)(CIUKI_REG_ESI), 5u},
    {"constant.CIUKI_REG_EBP", (uint32_t)(CIUKI_REG_EBP), 6u},
    {"constant.CIUKI_REG_ESP", (uint32_t)(CIUKI_REG_ESP), 7u},
    {"constant.CIUKI_REG_EBX", (uint32_t)(CIUKI_REG_EBX), 8u},
    {"constant.CIUKI_REG_EDX", (uint32_t)(CIUKI_REG_EDX), 9u},
    {"constant.CIUKI_REG_ECX", (uint32_t)(CIUKI_REG_ECX), 10u},
    {"constant.CIUKI_REG_EAX", (uint32_t)(CIUKI_REG_EAX), 11u},
    {"constant.CIUKI_REG_VECTOR", (uint32_t)(CIUKI_REG_VECTOR), 12u},
    {"constant.CIUKI_REG_ERROR", (uint32_t)(CIUKI_REG_ERROR), 13u},
    {"constant.CIUKI_REG_EIP", (uint32_t)(CIUKI_REG_EIP), 14u},
    {"constant.CIUKI_REG_CS", (uint32_t)(CIUKI_REG_CS), 15u},
    {"constant.CIUKI_REG_EFLAGS", (uint32_t)(CIUKI_REG_EFLAGS), 16u},
    {"constant.CIUKI_REG_USER_ESP", (uint32_t)(CIUKI_REG_USER_ESP), 17u},
    {"constant.CIUKI_REG_SS", (uint32_t)(CIUKI_REG_SS), 18u},
    {"constant.CIUKI_PTHREAD_ONCE_INIT", (uint32_t)(CIUKI_PTHREAD_ONCE_INIT), 0u},
    {"constant.CIUKI_SYS_EXIT", (uint32_t)(CIUKI_SYS_EXIT), 0u},
    {"constant.CIUKI_SYS_YIELD", (uint32_t)(CIUKI_SYS_YIELD), 1u},
    {"constant.CIUKI_SYS_DEBUG_WRITE", (uint32_t)(CIUKI_SYS_DEBUG_WRITE), 2u},
    {"constant.CIUKI_SYS_PROBE_REPORT", (uint32_t)(CIUKI_SYS_PROBE_REPORT), 3u},
    {"constant.CIUKI_SYS_SLEEP_MS", (uint32_t)(CIUKI_SYS_SLEEP_MS), 4u},
    {"constant.CIUKI_SYS_PROBE_QUERY", (uint32_t)(CIUKI_SYS_PROBE_QUERY), 5u},
    {"constant.CIUKI_SYS_RESERVED_6", (uint32_t)(CIUKI_SYS_RESERVED_6), 6u},
    {"constant.CIUKI_SYS_RESERVED_7", (uint32_t)(CIUKI_SYS_RESERVED_7), 7u},
    {"constant.CIUKI_SYS_RESERVED_8", (uint32_t)(CIUKI_SYS_RESERVED_8), 8u},
    {"constant.CIUKI_SYS_RESERVED_9", (uint32_t)(CIUKI_SYS_RESERVED_9), 9u},
    {"constant.CIUKI_SYS_RESERVED_10", (uint32_t)(CIUKI_SYS_RESERVED_10), 10u},
    {"constant.CIUKI_SYS_RESERVED_11", (uint32_t)(CIUKI_SYS_RESERVED_11), 11u},
    {"constant.CIUKI_SYS_RESERVED_12", (uint32_t)(CIUKI_SYS_RESERVED_12), 12u},
    {"constant.CIUKI_SYS_RESERVED_13", (uint32_t)(CIUKI_SYS_RESERVED_13), 13u},
    {"constant.CIUKI_SYS_RESERVED_14", (uint32_t)(CIUKI_SYS_RESERVED_14), 14u},
    {"constant.CIUKI_SYS_RESERVED_15", (uint32_t)(CIUKI_SYS_RESERVED_15), 15u},
    {"constant.CIUKI_SYS_SPAWN", (uint32_t)(CIUKI_SYS_SPAWN), 16u},
    {"constant.CIUKI_SYS_WAITPID", (uint32_t)(CIUKI_SYS_WAITPID), 17u},
    {"constant.CIUKI_SYS_GETPID", (uint32_t)(CIUKI_SYS_GETPID), 18u},
    {"constant.CIUKI_SYS_GETPPID", (uint32_t)(CIUKI_SYS_GETPPID), 19u},
    {"constant.CIUKI_SYS_THREAD_CREATE", (uint32_t)(CIUKI_SYS_THREAD_CREATE), 20u},
    {"constant.CIUKI_SYS_THREAD_EXIT", (uint32_t)(CIUKI_SYS_THREAD_EXIT), 21u},
    {"constant.CIUKI_SYS_TLS_SET", (uint32_t)(CIUKI_SYS_TLS_SET), 22u},
    {"constant.CIUKI_SYS_WAIT_WORD", (uint32_t)(CIUKI_SYS_WAIT_WORD), 23u},
    {"constant.CIUKI_SYS_WAKE_WORD", (uint32_t)(CIUKI_SYS_WAKE_WORD), 24u},
    {"constant.CIUKI_SYS_MMAP", (uint32_t)(CIUKI_SYS_MMAP), 25u},
    {"constant.CIUKI_SYS_MUNMAP", (uint32_t)(CIUKI_SYS_MUNMAP), 26u},
    {"constant.CIUKI_SYS_MPROTECT", (uint32_t)(CIUKI_SYS_MPROTECT), 27u},
    {"constant.CIUKI_SYS_BRK", (uint32_t)(CIUKI_SYS_BRK), 28u},
    {"constant.CIUKI_SYS_OPEN", (uint32_t)(CIUKI_SYS_OPEN), 29u},
    {"constant.CIUKI_SYS_READ", (uint32_t)(CIUKI_SYS_READ), 30u},
    {"constant.CIUKI_SYS_WRITE", (uint32_t)(CIUKI_SYS_WRITE), 31u},
    {"constant.CIUKI_SYS_PREAD", (uint32_t)(CIUKI_SYS_PREAD), 32u},
    {"constant.CIUKI_SYS_PWRITE", (uint32_t)(CIUKI_SYS_PWRITE), 33u},
    {"constant.CIUKI_SYS_LSEEK64", (uint32_t)(CIUKI_SYS_LSEEK64), 34u},
    {"constant.CIUKI_SYS_CLOSE", (uint32_t)(CIUKI_SYS_CLOSE), 35u},
    {"constant.CIUKI_SYS_FSTAT", (uint32_t)(CIUKI_SYS_FSTAT), 36u},
    {"constant.CIUKI_SYS_STAT", (uint32_t)(CIUKI_SYS_STAT), 37u},
    {"constant.CIUKI_SYS_GETDENTS", (uint32_t)(CIUKI_SYS_GETDENTS), 38u},
    {"constant.CIUKI_SYS_MKDIR", (uint32_t)(CIUKI_SYS_MKDIR), 39u},
    {"constant.CIUKI_SYS_RMDIR", (uint32_t)(CIUKI_SYS_RMDIR), 40u},
    {"constant.CIUKI_SYS_RENAME", (uint32_t)(CIUKI_SYS_RENAME), 41u},
    {"constant.CIUKI_SYS_UNLINK", (uint32_t)(CIUKI_SYS_UNLINK), 42u},
    {"constant.CIUKI_SYS_DUP", (uint32_t)(CIUKI_SYS_DUP), 43u},
    {"constant.CIUKI_SYS_DUP2", (uint32_t)(CIUKI_SYS_DUP2), 44u},
    {"constant.CIUKI_SYS_FCNTL", (uint32_t)(CIUKI_SYS_FCNTL), 45u},
    {"constant.CIUKI_SYS_FSYNC", (uint32_t)(CIUKI_SYS_FSYNC), 46u},
    {"constant.CIUKI_SYS_FTRUNCATE", (uint32_t)(CIUKI_SYS_FTRUNCATE), 47u},
    {"constant.CIUKI_SYS_GETCWD", (uint32_t)(CIUKI_SYS_GETCWD), 48u},
    {"constant.CIUKI_SYS_CHDIR", (uint32_t)(CIUKI_SYS_CHDIR), 49u},
    {"constant.CIUKI_SYS_CLOCK_GETTIME", (uint32_t)(CIUKI_SYS_CLOCK_GETTIME), 50u},
    {"constant.CIUKI_SYS_NANOSLEEP", (uint32_t)(CIUKI_SYS_NANOSLEEP), 51u},
    {"constant.CIUKI_SYS_SIGACTION", (uint32_t)(CIUKI_SYS_SIGACTION), 52u},
    {"constant.CIUKI_SYS_SIGPROCMASK", (uint32_t)(CIUKI_SYS_SIGPROCMASK), 53u},
    {"constant.CIUKI_SYS_KILL", (uint32_t)(CIUKI_SYS_KILL), 54u},
    {"constant.CIUKI_SYS_SIGRETURN", (uint32_t)(CIUKI_SYS_SIGRETURN), 55u},
    {"constant.CIUKI_SYS_UNAME", (uint32_t)(CIUKI_SYS_UNAME), 56u},
    {"constant.CIUKI_SYS_SURFACE_CREATE", (uint32_t)(CIUKI_SYS_SURFACE_CREATE), 57u},
    {"constant.CIUKI_SYS_SURFACE_MAP", (uint32_t)(CIUKI_SYS_SURFACE_MAP), 58u},
    {"constant.CIUKI_SYS_SURFACE_INFO", (uint32_t)(CIUKI_SYS_SURFACE_INFO), 59u},
    {"constant.CIUKI_SYS_PRESENT", (uint32_t)(CIUKI_SYS_PRESENT), 60u},
    {"constant.CIUKI_SYS_INPUT_READ", (uint32_t)(CIUKI_SYS_INPUT_READ), 61u},
    {"constant.CIUKI_SYS_CHANNEL_PAIR", (uint32_t)(CIUKI_SYS_CHANNEL_PAIR), 62u},
    {"constant.CIUKI_SYS_CHANNEL_SEND", (uint32_t)(CIUKI_SYS_CHANNEL_SEND), 63u},
    {"constant.CIUKI_SYS_CHANNEL_RECV", (uint32_t)(CIUKI_SYS_CHANNEL_RECV), 64u},
    {"constant.CIUKI_SYS_THREAD_JOIN", (uint32_t)(CIUKI_SYS_THREAD_JOIN), 65u},
    {"constant.CIUKI_SYS_THREAD_DETACH", (uint32_t)(CIUKI_SYS_THREAD_DETACH), 66u},
    {"constant.CIUKI_SYS_DISPLAY_INFO", (uint32_t)(CIUKI_SYS_DISPLAY_INFO), 67u},
    {"constant.CIUKI_SYS_THREAD_KILL", (uint32_t)(CIUKI_SYS_THREAD_KILL), 68u},
    {"sizeof.ciuki_size_t", (uint32_t)(sizeof(ciuki_size_t)), 4u},
    {"sizeof.ciuki_uintptr_t", (uint32_t)(sizeof(ciuki_uintptr_t)), 4u},
    {"sizeof.ciuki_ssize_t", (uint32_t)(sizeof(ciuki_ssize_t)), 4u},
    {"sizeof.ciuki_ptrdiff_t", (uint32_t)(sizeof(ciuki_ptrdiff_t)), 4u},
    {"sizeof.ciuki_pid_t", (uint32_t)(sizeof(ciuki_pid_t)), 4u},
    {"sizeof.ciuki_off_t", (uint32_t)(sizeof(ciuki_off_t)), 8u},
    {"sizeof.ciuki_time_t", (uint32_t)(sizeof(ciuki_time_t)), 8u},
    {"sizeof.ciuki_clock_t", (uint32_t)(sizeof(ciuki_clock_t)), 8u},
    {"sizeof.ciuki_ino_t", (uint32_t)(sizeof(ciuki_ino_t)), 8u},
    {"sizeof.ciuki_mode_t", (uint32_t)(sizeof(ciuki_mode_t)), 4u},
    {"sizeof.ciuki_nlink_t", (uint32_t)(sizeof(ciuki_nlink_t)), 4u},
    {"sizeof.ciuki_uid_t", (uint32_t)(sizeof(ciuki_uid_t)), 4u},
    {"sizeof.ciuki_gid_t", (uint32_t)(sizeof(ciuki_gid_t)), 4u},
    {"sizeof.ciuki_dev_t", (uint32_t)(sizeof(ciuki_dev_t)), 4u},
    {"sizeof.ciuki_blksize_t", (uint32_t)(sizeof(ciuki_blksize_t)), 4u},
    {"sizeof.ciuki_blkcnt_t", (uint32_t)(sizeof(ciuki_blkcnt_t)), 8u},
    {"sizeof.ciuki_pthread_t", (uint32_t)(sizeof(ciuki_pthread_t)), 4u},
    {"sizeof.ciuki_sigset_t", (uint32_t)(sizeof(ciuki_sigset_t)), 8u},
    {"sizeof.ciuki_pthread_mutex_t", (uint32_t)(sizeof(ciuki_pthread_mutex_t)), 32u},
    {"sizeof.ciuki_pthread_cond_t", (uint32_t)(sizeof(ciuki_pthread_cond_t)), 16u},
    {"sizeof.ciuki_pthread_attr_t", (uint32_t)(sizeof(ciuki_pthread_attr_t)), 16u},
    {"sizeof.ciuki_pthread_mutexattr_t", (uint32_t)(sizeof(ciuki_pthread_mutexattr_t)), 8u},
    {"sizeof.ciuki_pthread_condattr_t", (uint32_t)(sizeof(ciuki_pthread_condattr_t)), 8u},
    {"sizeof.ciuki_pthread_once_t", (uint32_t)(sizeof(ciuki_pthread_once_t)), 4u},
    {"sizeof.ciuki_timespec", (uint32_t)(sizeof(struct ciuki_timespec)), 16u},
    {"alignof.ciuki_timespec", (uint32_t)(_Alignof(struct ciuki_timespec)), 4u},
    {"offsetof.ciuki_timespec.tv_sec", (uint32_t)(__builtin_offsetof(struct ciuki_timespec, tv_sec)), 0u},
    {"offsetof.ciuki_timespec.tv_nsec", (uint32_t)(__builtin_offsetof(struct ciuki_timespec, tv_nsec)), 8u},
    {"offsetof.ciuki_timespec.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_timespec, reserved)), 12u},
    {"sizeof.ciuki_timeval", (uint32_t)(sizeof(struct ciuki_timeval)), 16u},
    {"alignof.ciuki_timeval", (uint32_t)(_Alignof(struct ciuki_timeval)), 4u},
    {"offsetof.ciuki_timeval.tv_sec", (uint32_t)(__builtin_offsetof(struct ciuki_timeval, tv_sec)), 0u},
    {"offsetof.ciuki_timeval.tv_usec", (uint32_t)(__builtin_offsetof(struct ciuki_timeval, tv_usec)), 8u},
    {"offsetof.ciuki_timeval.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_timeval, reserved)), 12u},
    {"sizeof.ciuki_stat", (uint32_t)(sizeof(struct ciuki_stat)), 104u},
    {"alignof.ciuki_stat", (uint32_t)(_Alignof(struct ciuki_stat)), 4u},
    {"offsetof.ciuki_stat.st_dev", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_dev)), 0u},
    {"offsetof.ciuki_stat.st_mode", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_mode)), 4u},
    {"offsetof.ciuki_stat.st_ino", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_ino)), 8u},
    {"offsetof.ciuki_stat.st_nlink", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_nlink)), 16u},
    {"offsetof.ciuki_stat.st_uid", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_uid)), 20u},
    {"offsetof.ciuki_stat.st_gid", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_gid)), 24u},
    {"offsetof.ciuki_stat.st_rdev", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_rdev)), 28u},
    {"offsetof.ciuki_stat.st_size", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_size)), 32u},
    {"offsetof.ciuki_stat.st_blksize", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_blksize)), 40u},
    {"offsetof.ciuki_stat.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_stat, reserved)), 44u},
    {"offsetof.ciuki_stat.st_blocks", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_blocks)), 48u},
    {"offsetof.ciuki_stat.st_atim", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_atim)), 56u},
    {"offsetof.ciuki_stat.st_mtim", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_mtim)), 72u},
    {"offsetof.ciuki_stat.st_ctim", (uint32_t)(__builtin_offsetof(struct ciuki_stat, st_ctim)), 88u},
    {"sizeof.ciuki_dirent", (uint32_t)(sizeof(struct ciuki_dirent)), 792u},
    {"alignof.ciuki_dirent", (uint32_t)(_Alignof(struct ciuki_dirent)), 4u},
    {"offsetof.ciuki_dirent.d_ino", (uint32_t)(__builtin_offsetof(struct ciuki_dirent, d_ino)), 0u},
    {"offsetof.ciuki_dirent.d_off", (uint32_t)(__builtin_offsetof(struct ciuki_dirent, d_off)), 8u},
    {"offsetof.ciuki_dirent.d_reclen", (uint32_t)(__builtin_offsetof(struct ciuki_dirent, d_reclen)), 16u},
    {"offsetof.ciuki_dirent.d_namlen", (uint32_t)(__builtin_offsetof(struct ciuki_dirent, d_namlen)), 18u},
    {"offsetof.ciuki_dirent.d_type", (uint32_t)(__builtin_offsetof(struct ciuki_dirent, d_type)), 20u},
    {"offsetof.ciuki_dirent.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_dirent, reserved)), 21u},
    {"offsetof.ciuki_dirent.d_name", (uint32_t)(__builtin_offsetof(struct ciuki_dirent, d_name)), 24u},
    {"sizeof.ciuki_spawn_fd", (uint32_t)(sizeof(struct ciuki_spawn_fd)), 8u},
    {"alignof.ciuki_spawn_fd", (uint32_t)(_Alignof(struct ciuki_spawn_fd)), 4u},
    {"offsetof.ciuki_spawn_fd.source", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_fd, source)), 0u},
    {"offsetof.ciuki_spawn_fd.target", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_fd, target)), 4u},
    {"sizeof.ciuki_spawn_args", (uint32_t)(sizeof(struct ciuki_spawn_args)), 32u},
    {"alignof.ciuki_spawn_args", (uint32_t)(_Alignof(struct ciuki_spawn_args)), 4u},
    {"offsetof.ciuki_spawn_args.size", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_args, size)), 0u},
    {"offsetof.ciuki_spawn_args.path", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_args, path)), 4u},
    {"offsetof.ciuki_spawn_args.argv", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_args, argv)), 8u},
    {"offsetof.ciuki_spawn_args.envp", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_args, envp)), 12u},
    {"offsetof.ciuki_spawn_args.fd_list", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_args, fd_list)), 16u},
    {"offsetof.ciuki_spawn_args.fd_count", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_args, fd_count)), 20u},
    {"offsetof.ciuki_spawn_args.flags", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_args, flags)), 24u},
    {"offsetof.ciuki_spawn_args.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_spawn_args, reserved)), 28u},
    {"sizeof.ciuki_thread_args", (uint32_t)(sizeof(struct ciuki_thread_args)), 32u},
    {"alignof.ciuki_thread_args", (uint32_t)(_Alignof(struct ciuki_thread_args)), 4u},
    {"offsetof.ciuki_thread_args.size", (uint32_t)(__builtin_offsetof(struct ciuki_thread_args, size)), 0u},
    {"offsetof.ciuki_thread_args.entry", (uint32_t)(__builtin_offsetof(struct ciuki_thread_args, entry)), 4u},
    {"offsetof.ciuki_thread_args.argument", (uint32_t)(__builtin_offsetof(struct ciuki_thread_args, argument)), 8u},
    {"offsetof.ciuki_thread_args.return_trampoline", (uint32_t)(__builtin_offsetof(struct ciuki_thread_args, return_trampoline)), 12u},
    {"offsetof.ciuki_thread_args.stack_bytes", (uint32_t)(__builtin_offsetof(struct ciuki_thread_args, stack_bytes)), 16u},
    {"offsetof.ciuki_thread_args.flags", (uint32_t)(__builtin_offsetof(struct ciuki_thread_args, flags)), 20u},
    {"offsetof.ciuki_thread_args.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_thread_args, reserved)), 24u},
    {"sizeof.ciuki_mmap_args", (uint32_t)(sizeof(struct ciuki_mmap_args)), 32u},
    {"alignof.ciuki_mmap_args", (uint32_t)(_Alignof(struct ciuki_mmap_args)), 4u},
    {"offsetof.ciuki_mmap_args.size", (uint32_t)(__builtin_offsetof(struct ciuki_mmap_args, size)), 0u},
    {"offsetof.ciuki_mmap_args.hint", (uint32_t)(__builtin_offsetof(struct ciuki_mmap_args, hint)), 4u},
    {"offsetof.ciuki_mmap_args.length", (uint32_t)(__builtin_offsetof(struct ciuki_mmap_args, length)), 8u},
    {"offsetof.ciuki_mmap_args.prot", (uint32_t)(__builtin_offsetof(struct ciuki_mmap_args, prot)), 12u},
    {"offsetof.ciuki_mmap_args.flags", (uint32_t)(__builtin_offsetof(struct ciuki_mmap_args, flags)), 16u},
    {"offsetof.ciuki_mmap_args.fd", (uint32_t)(__builtin_offsetof(struct ciuki_mmap_args, fd)), 20u},
    {"offsetof.ciuki_mmap_args.offset", (uint32_t)(__builtin_offsetof(struct ciuki_mmap_args, offset)), 24u},
    {"sizeof.ciuki_sigaction", (uint32_t)(sizeof(struct ciuki_sigaction)), 24u},
    {"alignof.ciuki_sigaction", (uint32_t)(_Alignof(struct ciuki_sigaction)), 4u},
    {"offsetof.ciuki_sigaction.handler", (uint32_t)(__builtin_offsetof(struct ciuki_sigaction, handler)), 0u},
    {"offsetof.ciuki_sigaction.flags", (uint32_t)(__builtin_offsetof(struct ciuki_sigaction, flags)), 4u},
    {"offsetof.ciuki_sigaction.mask", (uint32_t)(__builtin_offsetof(struct ciuki_sigaction, mask)), 8u},
    {"offsetof.ciuki_sigaction.restorer", (uint32_t)(__builtin_offsetof(struct ciuki_sigaction, restorer)), 16u},
    {"offsetof.ciuki_sigaction.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_sigaction, reserved)), 20u},
    {"sizeof.ciuki_siginfo", (uint32_t)(sizeof(struct ciuki_siginfo)), 32u},
    {"alignof.ciuki_siginfo", (uint32_t)(_Alignof(struct ciuki_siginfo)), 4u},
    {"offsetof.ciuki_siginfo.signo", (uint32_t)(__builtin_offsetof(struct ciuki_siginfo, signo)), 0u},
    {"offsetof.ciuki_siginfo.code", (uint32_t)(__builtin_offsetof(struct ciuki_siginfo, code)), 4u},
    {"offsetof.ciuki_siginfo.error", (uint32_t)(__builtin_offsetof(struct ciuki_siginfo, error)), 8u},
    {"offsetof.ciuki_siginfo.sender_pid", (uint32_t)(__builtin_offsetof(struct ciuki_siginfo, sender_pid)), 12u},
    {"offsetof.ciuki_siginfo.fault_addr", (uint32_t)(__builtin_offsetof(struct ciuki_siginfo, fault_addr)), 16u},
    {"offsetof.ciuki_siginfo.vector", (uint32_t)(__builtin_offsetof(struct ciuki_siginfo, vector)), 20u},
    {"offsetof.ciuki_siginfo.trap_error", (uint32_t)(__builtin_offsetof(struct ciuki_siginfo, trap_error)), 24u},
    {"offsetof.ciuki_siginfo.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_siginfo, reserved)), 28u},
    {"sizeof.ciuki_utsname", (uint32_t)(sizeof(struct ciuki_utsname)), 336u},
    {"alignof.ciuki_utsname", (uint32_t)(_Alignof(struct ciuki_utsname)), 4u},
    {"offsetof.ciuki_utsname.sysname", (uint32_t)(__builtin_offsetof(struct ciuki_utsname, sysname)), 0u},
    {"offsetof.ciuki_utsname.nodename", (uint32_t)(__builtin_offsetof(struct ciuki_utsname, nodename)), 65u},
    {"offsetof.ciuki_utsname.release", (uint32_t)(__builtin_offsetof(struct ciuki_utsname, release)), 130u},
    {"offsetof.ciuki_utsname.version", (uint32_t)(__builtin_offsetof(struct ciuki_utsname, version)), 195u},
    {"offsetof.ciuki_utsname.machine", (uint32_t)(__builtin_offsetof(struct ciuki_utsname, machine)), 260u},
    {"offsetof.ciuki_utsname.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_utsname, reserved)), 325u},
    {"offsetof.ciuki_utsname.abi_version", (uint32_t)(__builtin_offsetof(struct ciuki_utsname, abi_version)), 328u},
    {"offsetof.ciuki_utsname.realtime_source", (uint32_t)(__builtin_offsetof(struct ciuki_utsname, realtime_source)), 332u},
    {"sizeof.ciuki_ucontext", (uint32_t)(sizeof(struct ciuki_ucontext)), 256u},
    {"alignof.ciuki_ucontext", (uint32_t)(_Alignof(struct ciuki_ucontext)), 4u},
    {"offsetof.ciuki_ucontext.size", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, size)), 0u},
    {"offsetof.ciuki_ucontext.flags", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, flags)), 4u},
    {"offsetof.ciuki_ucontext.link", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, link)), 8u},
    {"offsetof.ciuki_ucontext.stack_base", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, stack_base)), 12u},
    {"offsetof.ciuki_ucontext.stack_bytes", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, stack_bytes)), 16u},
    {"offsetof.ciuki_ucontext.stack_flags", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, stack_flags)), 20u},
    {"offsetof.ciuki_ucontext.mask", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, mask)), 24u},
    {"offsetof.ciuki_ucontext.gregs", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs)), 32u},
    {"offsetof.ciuki_ucontext.cr2", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, cr2)), 108u},
    {"offsetof.ciuki_ucontext.fp_format", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, fp_format)), 112u},
    {"offsetof.ciuki_ucontext.fp_state", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, fp_state)), 116u},
    {"offsetof.ciuki_ucontext.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, reserved)), 224u},
    {"offsetof.ciuki_ucontext.gregs[0]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[0])), 32u},
    {"offsetof.ciuki_ucontext.gregs[1]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[1])), 36u},
    {"offsetof.ciuki_ucontext.gregs[2]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[2])), 40u},
    {"offsetof.ciuki_ucontext.gregs[3]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[3])), 44u},
    {"offsetof.ciuki_ucontext.gregs[4]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[4])), 48u},
    {"offsetof.ciuki_ucontext.gregs[5]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[5])), 52u},
    {"offsetof.ciuki_ucontext.gregs[6]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[6])), 56u},
    {"offsetof.ciuki_ucontext.gregs[7]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[7])), 60u},
    {"offsetof.ciuki_ucontext.gregs[8]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[8])), 64u},
    {"offsetof.ciuki_ucontext.gregs[9]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[9])), 68u},
    {"offsetof.ciuki_ucontext.gregs[10]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[10])), 72u},
    {"offsetof.ciuki_ucontext.gregs[11]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[11])), 76u},
    {"offsetof.ciuki_ucontext.gregs[12]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[12])), 80u},
    {"offsetof.ciuki_ucontext.gregs[13]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[13])), 84u},
    {"offsetof.ciuki_ucontext.gregs[14]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[14])), 88u},
    {"offsetof.ciuki_ucontext.gregs[15]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[15])), 92u},
    {"offsetof.ciuki_ucontext.gregs[16]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[16])), 96u},
    {"offsetof.ciuki_ucontext.gregs[17]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[17])), 100u},
    {"offsetof.ciuki_ucontext.gregs[18]", (uint32_t)(__builtin_offsetof(struct ciuki_ucontext, gregs[18])), 104u},
    {"sizeof.ciuki_signal_frame", (uint32_t)(sizeof(struct ciuki_signal_frame)), 320u},
    {"alignof.ciuki_signal_frame", (uint32_t)(_Alignof(struct ciuki_signal_frame)), 4u},
    {"offsetof.ciuki_signal_frame.restorer", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, restorer)), 0u},
    {"offsetof.ciuki_signal_frame.signo", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, signo)), 4u},
    {"offsetof.ciuki_signal_frame.siginfo_ptr", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, siginfo_ptr)), 8u},
    {"offsetof.ciuki_signal_frame.context_ptr", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, context_ptr)), 12u},
    {"offsetof.ciuki_signal_frame.size", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, size)), 16u},
    {"offsetof.ciuki_signal_frame.version", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, version)), 20u},
    {"offsetof.ciuki_signal_frame.token", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, token)), 24u},
    {"offsetof.ciuki_signal_frame.info", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, info)), 32u},
    {"offsetof.ciuki_signal_frame.context", (uint32_t)(__builtin_offsetof(struct ciuki_signal_frame, context)), 64u},
    {"sizeof.ciuki_tcb", (uint32_t)(sizeof(struct ciuki_tcb)), 64u},
    {"alignof.ciuki_tcb", (uint32_t)(_Alignof(struct ciuki_tcb)), 4u},
    {"offsetof.ciuki_tcb.self", (uint32_t)(__builtin_offsetof(struct ciuki_tcb, self)), 0u},
    {"offsetof.ciuki_tcb.tid", (uint32_t)(__builtin_offsetof(struct ciuki_tcb, tid)), 4u},
    {"offsetof.ciuki_tcb.reent", (uint32_t)(__builtin_offsetof(struct ciuki_tcb, reent)), 8u},
    {"offsetof.ciuki_tcb.pthread_private", (uint32_t)(__builtin_offsetof(struct ciuki_tcb, pthread_private)), 12u},
    {"offsetof.ciuki_tcb.stack_base", (uint32_t)(__builtin_offsetof(struct ciuki_tcb, stack_base)), 16u},
    {"offsetof.ciuki_tcb.stack_bytes", (uint32_t)(__builtin_offsetof(struct ciuki_tcb, stack_bytes)), 20u},
    {"offsetof.ciuki_tcb.flags", (uint32_t)(__builtin_offsetof(struct ciuki_tcb, flags)), 24u},
    {"offsetof.ciuki_tcb.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_tcb, reserved)), 28u},
    {"sizeof.ciuki_surface_info", (uint32_t)(sizeof(struct ciuki_surface_info)), 24u},
    {"alignof.ciuki_surface_info", (uint32_t)(_Alignof(struct ciuki_surface_info)), 4u},
    {"offsetof.ciuki_surface_info.size", (uint32_t)(__builtin_offsetof(struct ciuki_surface_info, size)), 0u},
    {"offsetof.ciuki_surface_info.width", (uint32_t)(__builtin_offsetof(struct ciuki_surface_info, width)), 4u},
    {"offsetof.ciuki_surface_info.height", (uint32_t)(__builtin_offsetof(struct ciuki_surface_info, height)), 8u},
    {"offsetof.ciuki_surface_info.stride", (uint32_t)(__builtin_offsetof(struct ciuki_surface_info, stride)), 12u},
    {"offsetof.ciuki_surface_info.format", (uint32_t)(__builtin_offsetof(struct ciuki_surface_info, format)), 16u},
    {"offsetof.ciuki_surface_info.allocation_bytes", (uint32_t)(__builtin_offsetof(struct ciuki_surface_info, allocation_bytes)), 20u},
    {"sizeof.ciuki_display_info", (uint32_t)(sizeof(struct ciuki_display_info)), 48u},
    {"alignof.ciuki_display_info", (uint32_t)(_Alignof(struct ciuki_display_info)), 4u},
    {"offsetof.ciuki_display_info.size", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, size)), 0u},
    {"offsetof.ciuki_display_info.width", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, width)), 4u},
    {"offsetof.ciuki_display_info.height", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, height)), 8u},
    {"offsetof.ciuki_display_info.pitch", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, pitch)), 12u},
    {"offsetof.ciuki_display_info.bpp", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, bpp)), 16u},
    {"offsetof.ciuki_display_info.red_size", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, red_size)), 20u},
    {"offsetof.ciuki_display_info.red_pos", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, red_pos)), 24u},
    {"offsetof.ciuki_display_info.green_size", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, green_size)), 28u},
    {"offsetof.ciuki_display_info.green_pos", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, green_pos)), 32u},
    {"offsetof.ciuki_display_info.blue_size", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, blue_size)), 36u},
    {"offsetof.ciuki_display_info.blue_pos", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, blue_pos)), 40u},
    {"offsetof.ciuki_display_info.generation", (uint32_t)(__builtin_offsetof(struct ciuki_display_info, generation)), 44u},
    {"sizeof.ciuki_rect", (uint32_t)(sizeof(struct ciuki_rect)), 24u},
    {"alignof.ciuki_rect", (uint32_t)(_Alignof(struct ciuki_rect)), 4u},
    {"offsetof.ciuki_rect.src_x", (uint32_t)(__builtin_offsetof(struct ciuki_rect, src_x)), 0u},
    {"offsetof.ciuki_rect.src_y", (uint32_t)(__builtin_offsetof(struct ciuki_rect, src_y)), 4u},
    {"offsetof.ciuki_rect.dst_x", (uint32_t)(__builtin_offsetof(struct ciuki_rect, dst_x)), 8u},
    {"offsetof.ciuki_rect.dst_y", (uint32_t)(__builtin_offsetof(struct ciuki_rect, dst_y)), 12u},
    {"offsetof.ciuki_rect.width", (uint32_t)(__builtin_offsetof(struct ciuki_rect, width)), 16u},
    {"offsetof.ciuki_rect.height", (uint32_t)(__builtin_offsetof(struct ciuki_rect, height)), 20u},
    {"sizeof.ciuki_input_event", (uint32_t)(sizeof(struct ciuki_input_event)), 40u},
    {"alignof.ciuki_input_event", (uint32_t)(_Alignof(struct ciuki_input_event)), 4u},
    {"offsetof.ciuki_input_event.sequence", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, sequence)), 0u},
    {"offsetof.ciuki_input_event.source", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, source)), 4u},
    {"offsetof.ciuki_input_event.generation", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, generation)), 8u},
    {"offsetof.ciuki_input_event.type", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, type)), 12u},
    {"offsetof.ciuki_input_event.monotonic_ns", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, monotonic_ns)), 16u},
    {"offsetof.ciuki_input_event.code", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, code)), 24u},
    {"offsetof.ciuki_input_event.value", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, value)), 28u},
    {"offsetof.ciuki_input_event.value2", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, value2)), 32u},
    {"offsetof.ciuki_input_event.lost_count", (uint32_t)(__builtin_offsetof(struct ciuki_input_event, lost_count)), 36u},
    {"sizeof.ciuki_message", (uint32_t)(sizeof(struct ciuki_message)), 288u},
    {"alignof.ciuki_message", (uint32_t)(_Alignof(struct ciuki_message)), 4u},
    {"offsetof.ciuki_message.length", (uint32_t)(__builtin_offsetof(struct ciuki_message, length)), 0u},
    {"offsetof.ciuki_message.fd_count", (uint32_t)(__builtin_offsetof(struct ciuki_message, fd_count)), 4u},
    {"offsetof.ciuki_message.fds", (uint32_t)(__builtin_offsetof(struct ciuki_message, fds)), 8u},
    {"offsetof.ciuki_message.sender_pid", (uint32_t)(__builtin_offsetof(struct ciuki_message, sender_pid)), 24u},
    {"offsetof.ciuki_message.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_message, reserved)), 28u},
    {"offsetof.ciuki_message.data", (uint32_t)(__builtin_offsetof(struct ciuki_message, data)), 32u},
    {"sizeof.ciuki_pthread_mutex", (uint32_t)(sizeof(struct ciuki_pthread_mutex)), 32u},
    {"alignof.ciuki_pthread_mutex", (uint32_t)(_Alignof(struct ciuki_pthread_mutex)), 4u},
    {"offsetof.ciuki_pthread_mutex.words", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_mutex, words)), 0u},
    {"sizeof.ciuki_pthread_cond", (uint32_t)(sizeof(struct ciuki_pthread_cond)), 16u},
    {"alignof.ciuki_pthread_cond", (uint32_t)(_Alignof(struct ciuki_pthread_cond)), 4u},
    {"offsetof.ciuki_pthread_cond.words", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_cond, words)), 0u},
    {"sizeof.ciuki_pthread_attr", (uint32_t)(sizeof(struct ciuki_pthread_attr)), 16u},
    {"alignof.ciuki_pthread_attr", (uint32_t)(_Alignof(struct ciuki_pthread_attr)), 4u},
    {"offsetof.ciuki_pthread_attr.stack_bytes", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_attr, stack_bytes)), 0u},
    {"offsetof.ciuki_pthread_attr.detached", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_attr, detached)), 4u},
    {"offsetof.ciuki_pthread_attr.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_attr, reserved)), 8u},
    {"sizeof.ciuki_pthread_mutexattr", (uint32_t)(sizeof(struct ciuki_pthread_mutexattr)), 8u},
    {"alignof.ciuki_pthread_mutexattr", (uint32_t)(_Alignof(struct ciuki_pthread_mutexattr)), 4u},
    {"offsetof.ciuki_pthread_mutexattr.type", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_mutexattr, type)), 0u},
    {"offsetof.ciuki_pthread_mutexattr.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_mutexattr, reserved)), 4u},
    {"sizeof.ciuki_pthread_condattr", (uint32_t)(sizeof(struct ciuki_pthread_condattr)), 8u},
    {"alignof.ciuki_pthread_condattr", (uint32_t)(_Alignof(struct ciuki_pthread_condattr)), 4u},
    {"offsetof.ciuki_pthread_condattr.clock_id", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_condattr, clock_id)), 0u},
    {"offsetof.ciuki_pthread_condattr.reserved", (uint32_t)(__builtin_offsetof(struct ciuki_pthread_condattr, reserved)), 4u},
};

static int fail(const char *key, const char *reason)
{
    fprintf(stderr, "abi layout: FAIL: %s: %s\n", key, reason);
    return 1;
}

int main(int argc, char **argv)
{
    /* The dump is a flat JSON object of unsigned integers. Parse it strictly:
     * reject missing/duplicate/extra keys and trailing data, not just mismatches.
     */
    const size_t count = sizeof(expectations) / sizeof(expectations[0]);
    unsigned char seen[sizeof(expectations) / sizeof(expectations[0])] = {0};
    FILE *input;
    size_t found = 0;
    int c;
    if (argc != 2) return fail("usage", "abi_layout_test target.json");
    input = fopen(argv[1], "r");
    if (!input) return fail(argv[1], "cannot open target dump");
    do { c = fgetc(input); } while (c == ' ' || c == '\n' || c == '\t' || c == '\r');
    if (c != '{') { fclose(input); return fail("JSON", "expected object"); }
    for (;;) {
        char key[160];
        unsigned long long value = 0;
        size_t length = 0, index;
        do { c = fgetc(input); } while (c == ' ' || c == '\n' || c == '\t' || c == '\r');
        if (c != '"') { fclose(input); return fail("JSON", "expected key"); }
        while ((c = fgetc(input)) != '"') {
            if (c < 32 || c == '\\' || length + 1 >= sizeof(key)) {
                fclose(input); return fail("JSON", "invalid key");
            }
            key[length++] = (char)c;
        }
        key[length] = '\0';
        do { c = fgetc(input); } while (c == ' ' || c == '\n' || c == '\t' || c == '\r');
        if (c != ':') { fclose(input); return fail(key, "expected colon"); }
        do { c = fgetc(input); } while (c == ' ' || c == '\n' || c == '\t' || c == '\r');
        if (c < '0' || c > '9') { fclose(input); return fail(key, "expected unsigned value"); }
        do {
            value = value * 10 + (unsigned)(c - '0');
            if (value > UINT32_MAX) { fclose(input); return fail(key, "value overflow"); }
            c = fgetc(input);
        } while (c >= '0' && c <= '9');
        for (index = 0; index < count; ++index)
            if (strcmp(key, expectations[index].key) == 0) break;
        if (index == count) { fclose(input); return fail(key, "unexpected target entry"); }
        if (seen[index]) { fclose(input); return fail(key, "duplicate target entry"); }
        seen[index] = 1;
        ++found;
        int check_native = 1;
#if !defined(__i386__)
        /* Native LP64 objects are not the target C model. Wire-record values
         * are still checked natively; the i686 dump checks target-only keys.
         */
        if (strncmp(key, "target.", 7) == 0) check_native = 0;
#endif
        if (value != expectations[index].expected ||
            (check_native && expectations[index].native != expectations[index].expected)) {
            fprintf(stderr, "abi layout: %s: target=%llu native=%u contract=%u\n",
                    key, value, expectations[index].native, expectations[index].expected);
            fclose(input); return 1;
        }
        while (c == ' ' || c == '\n' || c == '\t' || c == '\r') c = fgetc(input);
        if (c == '}') break;
        if (c != ',') { fclose(input); return fail(key, "expected comma or end"); }
    }
    do { c = fgetc(input); } while (c == ' ' || c == '\n' || c == '\t' || c == '\r');
    if (c != EOF || ferror(input)) { fclose(input); return fail("JSON", "trailing data/read error"); }
    fclose(input);
    for (size_t i = 0; i < count; ++i)
        if (!seen[i]) return fail(expectations[i].key, "missing target entry");
    if (found != count) return fail("JSON", "wrong entry count");

    /* Function/aggregate macros cannot appear in the numeric object table. */
    const struct ciuki_pthread_mutex mutex = CIUKI_PTHREAD_MUTEX_INITIALIZER;
    const struct ciuki_pthread_cond cond = CIUKI_PTHREAD_COND_INITIALIZER;
    for (size_t i = 0; i < 8; ++i)
        if (mutex.words[i] != 0) return fail("mutex initializer", "nonzero word");
    for (size_t i = 0; i < 4; ++i)
        if (cond.words[i] != 0) return fail("condition initializer", "nonzero word");
    if (!WIFEXITED(9472) || WEXITSTATUS(9472) != 37 || WIFSIGNALED(9472) ||
        WIFEXITED(11) || !WIFSIGNALED(11) || WTERMSIG(11) != 11 ||
        CIUKI_SIGBIT(SIGINT) != UINT64_C(2) ||
        CIUKI_SIGBIT(SIGCHLD) != UINT64_C(65536))
        return fail("signal/wait macros", "contract result differs");
    printf("abi layout: PASS (%zu target/native contract checks; off_t=8 time_t=8)\n", count);
    return 0;
}
