#!/usr/bin/env bash
# Build LFN.COM, the long file name extension of the CiukiDOS kernel
# (src/lfn, docs/design-long-file-names-2026-09-30.md).
#   scripts/build_lfn.sh KERNEL_LISTING [OUTPUT_DIR]
# The listing is the one of the kernel the image ships (build_full.sh writes
# build/full/obj/ciukidos.lst): the extension calls the kernel's disk
# routines and reads its FAT cache flags at the addresses listed there, and
# checks them at install.
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
LISTING="${1:?kernel listing}"
OUT="${2:-build/full/obj/lfn}"
export WATCOM="${WATCOM:-/opt/watcom}"
export PATH="$WATCOM/binl64:$PATH"
export INCLUDE="$WATCOM/h"
mkdir -p "$OUT"
python3 - "$LISTING" "$OUT/lfn_kernel.inc" <<'PY'
import re, sys
lines = open(sys.argv[1], errors='replace').read().splitlines()
addr = re.compile(r'\s*\d+\s+([0-9A-F]{8})\s+([0-9A-F]+)')
data = {'dos_indos_flag': 'KL_INDOS', 'fat_cache_valid': 'KL_FAT_VALID',
        'fat_cache_dirty': 'KL_FAT_DIRTY', 'fat_cache_sector': 'KL_FAT_SECTOR'}
code = {'read_sector_lba32': 'KL_READ', 'write_sector_lba32': 'KL_WRITE'}
out, sig = {}, {}
for i, line in enumerate(lines):
    m = re.match(r'\s*\d+\s+([0-9A-F]{8})\s+\S+\s+(?:<\d+>\s+)?(\w+)\s+d[bw]\b', line)
    if m and m.group(2) in data:
        out[data[m.group(2)]] = int(m.group(1), 16)
    m = re.match(r'\s*\d+\s+(?:<\d+>\s+)?(\w+):\s*(;.*)?$', line)
    if not m:
        continue
    name = m.group(1)
    if name in code:
        n = addr.match(lines[i + 1])
        if not n:
            continue
        out[code[name]] = int(n.group(1), 16)
        # The routine's first bytes (push bp; mov bp,42xxh), checked at install.
        raw = n.group(2) + addr.match(lines[i + 2]).group(2)
        sig[code[name] + '_SIG'] = int.from_bytes(bytes.fromhex(raw[:8]), 'little')
    if name == 'kernel_runtime_identity_service':
        for follow in lines[i + 1:i + 6]:
            n = addr.match(follow)
            if n and follow.rstrip().endswith('retf'):
                out['KL_RETF'] = int(n.group(1), 16)
                break
want = ['KL_INDOS', 'KL_FAT_VALID', 'KL_FAT_DIRTY', 'KL_FAT_SECTOR', 'KL_READ', 'KL_WRITE', 'KL_RETF']
missing = [k for k in want if k not in out]
if missing:
    sys.exit(f'build_lfn: {sys.argv[1]}: missing {missing}')
src = open('src/boot/floppy_stage1.asm').read()
seg = re.search(r'%ifdef CIUKIDOS_KERNEL_BUILD.*?%define DOS_FAT_BUF_SEG\s+(0x[0-9A-Fa-f]+)', src, re.S)
text = ['; Generated by scripts/build_lfn.sh from ' + sys.argv[1]]
text += [f'{k} equ 0{v:X}h' for k, v in out.items()]
text += [f'{k} equ 0{v:08X}h' for k, v in sig.items()]
text.append(f'KL_FAT_BUF_SEG equ {seg.group(1)}')
open(sys.argv[2], 'w').write('\n'.join(text) + '\n')
PY
CFLAGS=(-q -2 -ms -s -zl -os -d0 -wx -we -zq -i=src/lfn)
nasm -f obj -I "$OUT/" src/lfn/lfn_start.asm -o "$OUT/lfn_start.obj"
wcc "${CFLAGS[@]}" -fo="$OUT/lfn.obj" src/lfn/lfn.c
wcc "${CFLAGS[@]}" -nt=ITEXT -nc=ICODE -fo="$OUT/lfn_init.obj" src/lfn/lfn_init.c
wlink option quiet format raw bin option offset=0x100 option start=start \
	option map="$OUT/lfn.map" name "$OUT/LFN.COM" \
	file "$OUT/lfn_start.obj,$OUT/lfn.obj,$OUT/lfn_init.obj"
python3 - "$OUT/LFN.COM" "$OUT/lfn.map" <<'PY'
import re, sys
image, mapfile = sys.argv[1], sys.argv[2]
text = open(mapfile).read()
m = re.search(r'resident_end\s*$', text, re.M)
size = len(open(image, 'rb').read())
res = None
for line in text.splitlines():
    if 'resident_end' in line:
        res = int(line.split(':')[-1].split()[0], 16) if ':' in line else None
if size > 0xF000:
    sys.exit(f'{image}: too large ({size} bytes)')
print(f'[build-lfn] {image}: {size} bytes' + (f', resident {res + 0x100 if res is not None else "?"} bytes' if res is not None else ''))
PY
